project:
  type: website
  output-dir: docs

website:
  title: "Jay Rajput"
  site-url: https://jaysinghr.github.io/
  description: "This is Jay's personal blog."
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
    right:
      - text: Blogs/Notebooks
        href: blog.qmd
      - icon: github
        href: https://github.com/jaysinghr
      - icon: twitter
        href: https://twitter.com/__Jay_Singh__
      - icon: linkedin
        href: https://www.linkedin.com/in/jaydeepsinh-rajput/
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true