---
title: "Here are some of the content that I shared with community"
description: "These includes notebooks, blogs, etc... If you found value in my notebook, I would greatly appreciate your support through an UPVOTE. Additionally, I welcome any constructive reviews or suggestions for improvement. Thank you for your consideration!"
categories: ["Python", "Visualization", "Callbacks", "Initializations", "Activations", "Optimizers", "Learner", "Augmentations", "Deep Learning"]
listing:
  sort: "date desc"
  type: default
  categories: true
  sort-ui: true
  filter-ui: true
  fields: [date, title, reading-time, description, categories]
  feed: true
page-layout: full
title-block-banner: false
---

## Python Callbacks: Which Not Everybody Knows

### Description

There is a very interesting thing I learnt which is to build our own Learner class. So Learner class is going to be a very general purpose training loop, which we can get it to do anything that we want it to do. And we gonna be creating things called callbacks to to make that happen.

### Link

[Python Callbacks: Kaggle Notebook](https://www.kaggle.com/code/anticsishere/python-callbacks-which-not-everybody-knows).

---

## Animal Classifier: Identifying 90 Different Animals with Fastai

### Description

Explore my animal classifier project, where I trained a deep learning model to identify 90 different animals. Leveraging the power of the Fastai library and the Fastbook tutorial, this project showcases the application of deep learning in image classification. Check out the notebook to dive into the details of the model training process and see the classifier in action. If you find it useful, feel free to give it a try and provide feedback!

### Link

[Animal Classifier: Kaggle Notebook](https://www.kaggle.com/code/anticsishere/animal-classifier).
[Animal Classifier: Hugging Face Space Link](https://huggingface.co/spaces/Jay-Rajput/Animal-Classifier).
